pipeline {
  agent any

  stages {
    stage('Initial checks') {
      steps {
        echo "Java version:"
        sh 'java --version'
        echo "Gradle version:"
        sh './gradlew version'
      }
    }
    stage('Compile') {
      steps {
        echo "Compiling project"
        sh '''
          chmod +x gradlew
          ./gradlew compileJava
        '''
      }
    }
    stage('Unit Tests') {
      steps {
        echo "Running unit tests"
        sh './gradlew test'
      }
    }
  }
}
